main.go
When loading config such error would occur. Probably because net.IP type
cannot be used as a key in map, and cannot be compared directly. That is why I
switched from array to map and used deep equality of reflect package to check
if default value is set.
=> Prevent "panic: runtime error: hash of unhashable type net.IP"

artifacts.go
This is a pull request to change something that you understand more than I do. In fact, you wrote the change!
=> Use new hostname library

main.go
Should probably add some tests...
=> Bug 1181524 - resolve with malformed-payload if artifact.expires < task.deadline

artifacts.go, artifacts_test.go, main.go
This now gzip compresses artifact log files. All other artifacts remain not gzip compressed. If all artifacts (not just log files) should be gzip compressed, let me know! :-)
Added check to existing test that artifacts have correct encoding.
=> Bug 1291249 - gzip log artifacts and set Content-Encoding in PUT to S3

.travis.yml, build.sh
=> Updated to use go 1.7 due to contester/runlib#5

all-unix-style.yml, artifacts.go, chain_of_trust.go, diskspace_all-unix-style.go, diskspace_windows.go, feature.go, garbagecollector.go, generated_all-unix-style.go, generated_windows.go, livelog.go, main.go, main_test.go, model.go, mounts.go, mounts_test.go, windows.yml
This is where I'll be doing the work. Not ready for review - but maybe useful for tracking progress. I'll ping when it is ready for review!
CC @jonasfj @gregarndt
=> Bug 1182451 - preloaded writable directory caches / empty writable directory caches / preloaded readonly directory mounts / preloaded readonly files

all-unix-style.yml, generated_all-unix-style.go, generated_windows.go, helper_all-unix-style_test.go, helper_windows_test.go, main.go, os_groups.go, os_groups_test.go, plat_all-unix-style.go, plat_windows.go, windows.yml
@grenade This should allow tasks to specify extra OS groups that their task user should be made a member of.
=> Bug 1306988 - add feature "OS Groups" 

main.go
@gregarndt Thanks for raising!
=> Bug 1323827: stop task reclaim timer when task completes naturally

main.go
I know there is more cleanup that could be done, but this is just to unhang the workers we have hanging at the moment.
=> Bug 1329617 - never drain timer channel when stopping a timer returned by time.AboutFunc

.taskcluster.yml
=> Fix for running .taskcluster.yml tasks against forked repos

all-unix-style.yml, windows.yml
Just some doc updates regarding artifact name/path meanings.
Thanks John!
=> Payload artifact schema doc additions

README.md, generated_windows.go, main.go, plat_windows.go, rdp_windows.go, windows.yml, worker_types/gecko-1-b-win2012-beta/userdata, worker_types/gecko-t-win10-64-beta/userdata, worker_types/gecko-t-win10-64-cu/userdata, worker_types/gecko-t-win10-64-gpu-b/userdata, worker_types/gecko-t-win7-32-beta/userdata, worker_types/gecko-t-win7-32-cu/userdata, worker_types/gecko-t-win7-32-gpu-b/userdata, worker_types/nss-win2012r2-new/userdata, worker_types/nss-win2012r2/userdata, worker_types/win2012r2-cu/userdata, worker_types/win2012r2/userdata, worker_types/win2016/userdata
See [bug 1172273](https://bugzil.la/1172273) for more information.
=> Bug 1172273 - native RDP feature

worker_types/ami-test-win2012r2/userdata, worker_types/ami-test-win7sp1/userdata, worker_types/nss-win2012r2-new/userdata, worker_types/nss-win2012r2/userdata, worker_types/win2012r2-cu/userdata, worker_types/win2012r2/userdata, worker_types/win2016/userdata
Tested on a Windows Server 2012 R2 EC2 instance.
CC @mykmelez @djmitche
=> Upgrade git from Git-1.9.5-preview20150319 to Git-2.16.2

artifacts_test.go, helper_test.go, main_test.go, mounts_test.go, os_groups_test.go, plat_windows_test.go, supersede_test.go, taskcluster_proxy_test.go, taskstatus_test.go, user_creation_windows_test.go
This is a cleanup of test internals, with no functional changes.
=> Refactored test internals

aws.go, aws_helper_test.go, aws_test.go, fileutil/fileutil.go, gwconfig/config.go, helper_test.go, main.go, taskstatus.go
I think this should do it. Not written any tests yet - will need to mock the termination endpoint to do that, I guess.
=> Bug 1180187 - listen for spot termination notice and abort task on discovery

aws_test.go, main.go
See https://mozilla.logbot.info/taskcluster/20180410#c14588279-c14588443
for more details
CC: @Archaeopteryx
=> Log command result as info not error

artifacts.go, artifacts_test.go, aws.go, chain_of_trust.go, gw-workers/main.go, helper_test.go, livelog.go, main.go, main_test.go, model.go, mounts.go, occ-workers/main.go, payload_test.go, sentry.go, taskstatus.go, testdata/resolvetask.go, update-ssl-creds/main.go, update-worker-type/update-worker-type.go, worker_types/all-worker-types/main.go, worker_types/refresh-gw-configs/main.go
=> Updated to use latest taskcluster-client-go library

README.md, chain_of_trust.go, main.go, refresh_readme.sh, release.sh
See [bug 1444118](https://bugzil.la/1444118) for context.
=> Bug 1444118 - Improve logging when chain of trust initialisation checks fail

all-unix-style.yml, generated_all-unix-style.go, generated_windows.go, windows.yml
See [bug 1456357](https://bugzil.la/1456357) for context. Thanks!
=> Bug 1456357 - remove references to http://schemas.taskcluster.net/generic-worker/v1/payload.json

main.go
This should reduce a lot of logging that looks like this:
```
May 02 09:32:06 t-yosemite-r7-380.test.releng.mdc1.mozilla.com generic-worker: 2018/05/02 00:32:06 Loaded file file-caches.json into object:
May 02 09:32:06 t-yosemite-r7-380.test.releng.mdc1.mozilla.com generic-worker: &main.CacheMap{"artifact:KEimHTYzRiynq6wkfO4lmw:public/build/mozharness.zip":(*main.Cache)(0x421dbd720), "artifact:J_eNC4VTRG-HFY3Zw3ac1w:public/build/mozharness.zip":(*main.Cache)(0x421dbc0f0), "artifact:SXuA7XnGRZiHtJntPB9JUw:public/build/mozharness.zip":(*main.Cache)(0x421c711d0), "artifact:YnDckRbxT7O2kamTJec7pg:public/build/mozharness.zip":(*main.Cache)(0x421dad180), "artifact:biYlIVBHR1m_Zu6f4tGulg:public/build/mozharness.zip":(*main.Cache)(0x421acb3b0), …
```
=> Bug 1452095 - don't log every file in worker cache on worker startup

.taskcluster.yml, .travis.yml, chain_of_trust_windows.go, helper_test.go, main.go, main_test.go, plat_windows.go, process/process_all-unix-style.go, process/process_windows.go
See [bug 1458873](https://bugzilla.mozilla.org/show_bug.cgi?id=1458873) for context.
=> Bug 1458873 - Fix task abortion

all-unix-style.yml, chain_of_trust.go, fileutil/fileutil.go, garbagecollector.go, generated_all-unix-style.go, generated_windows.go, helper_test.go, main.go, mounts.go, mounts_test.go, taskstatus.go, windows.yml
See [bug 1459376](https://bugzil.la/1459376) for context.
=> Bug 1459376 - log actions taken by mounts feature, and validate SHA256 of content

livelog/livelog.go
=> Close livelog channels when finished with them

mounts.go, mounts_test.go
See [bug 1468155](https://bugzil.la/1468155) for context.
=> Bug 1468155 - check mounted artifact content's tasks are task dependencies

gwconfig/config.go, helper_test.go, main.go, mounts.go, sentry.go
Thanks Greg. Quick as you can, please! 😉
=> Added properties for auth/purgecache/queue base url

mounts.go, mounts_test.go
See [bug 1506621](https://bugzil.la/1506621) for context. Thanks!
=> Bug 1506621 - update code to use new (v3) github.com/mholt/archiver interface

.taskcluster.yml, plat_windows.go, win32/win32_windows.go
See [bug 1493688](https://bugzil.la/1493688) for context.
CC @grenade
=> Bug 1493688 - make redirecting app data folders a non-critical error

worker_types/nss-win2012r2-new/userdata, worker_types/nss-win2012r2/userdata, worker_types/win2012r2/userdata
See [bug 1523911](https://bugzil.la/1523911) for details.
=> Bug 1523911 - Upgrade to taskcluster-proxy 5.0.1 on all worker types

README.md, aws_helper_test.go, gcp.go, gcp_helper_test.go, main.go, plat_windows.go
See [bug 1524792](https://bugzil.la/1524792) for context. Thanks!
=> Bug 1524792 - bring --configure-for-gcp option up-to-date with recent changes

main.go
When generic-worker is run from an AWS Provisioner spawned instance, the worker builds its config by communicating with the AWS EC2 metadata service, the taskcluster AWS Provisioner, and the taskcluster secrets service.
If it didn't persist its config to the file system, the worker config wouldn't be available after a reboot, since, for example, we intentionally delete AWS credentials from the AWS Provisioner after fetching them, so that a malicious task doesn't have access to them via a secret key available from the instance's user data.
However, on workers where the config file is not fetched over the network but is provided locally on the file system, it is not ideal to rewrite the config file to disk after loading it. The original motivation for replacing the config file on startup …
=> Bug 1531457 - don't replace generic-worker.config if already exists

README.md
(this is copied from websocktunnel)
=> Add a bit of text pointing developers at how to modify dependencies

main.go, main_test.go, plat_all-unix-style.go, plat_windows.go
Looks like I inadvertently broke this test when I landed [bug 1533694](https://bugzil.la/1533694) in release 14.0.2.
=> Fix test TestRemoveTaskDirs

main.go
See [bug 1548829](https://bugzil.la/1548829) for more context.
=> Bug 1548829 - include provisionerId in task log header

main.go, plat_all-unix-style.go
See [bug 1552465](https://bugzil.la/1552465) for details.
=> Bug 1552465 - only prepare new task environment when task has been claimed

artifacts.go
See [bug 1562964](https://bugzil.la/1562964) for context.
=> Bug 1562964 - log HTTP response body when bad HTTP status code uploading artifacts

README.md, main.go, usage.go
See [bug 1564354](https://bugzil.la/1564354) for context.
=> Bug 1564354 - use sentry project 'generic-worker' by default

chain_of_trust.go, chain_of_trust_posix.go, chain_of_trust_windows.go, process/multiuser_simple.go
See [bug 1564361](https://bugzil.la/1564361) for context.
=> Bug 1564361 - log system errors when not able to check whether chain of trust key is readable by task user

.taskcluster.yml, README.md, build.sh, gotestcover.sh, helper_test.go, main_test.go, mounts_test.go, mounts_windows_test.go, multiuser_test.go, taskcluster_proxy_broken_on_docker_test.go, tcproxy/tcproxy_test.go, testutil/testutil.go
See [bug 1564831](https://bugzil.la/1564831) for context. Thanks!
=> Bug 1564831 - require GW_SKIP_* env vars to be set to skip tests

.gitignore
See [bug 1565338](https://bugzil.la/1565338) for context. Thanks!
=> Bug 1565338 - avoid worker-state pollution between tests

fileutil/fileutil_posix.go, fileutil/fileutil_posix_test.go
See [bug 1566159](https://bugzil.la/1566159) for context.
=> Bug 1566159 - determine uid/gid of current user by executing /usr/bin/id

main.go, runtime/runtime_darwin.go
Not worthy of a bug, or probably even a review, but here it is anyway...
=> Trivial logging changes

artifacts.go, artifacts_test.go, chain_of_trust.go, livelog.go, rdp_windows.go, supersede.go
See [bug 1568782](https://bugzil.la/1568782) for context. Thanks!
=> Bug 1568782 - error artifacts do not have a content type

expose/proxy_test.go, expose/statelessdns_test.go, expose/wsproxy.go, expose/wst_test.go, helper_test.go, livelog/livelog.go, livelog/livelog_test.go, mounts.go, supersede_test.go, taskcluster_proxy.go, worker_types/all-worker-types/main.go, worker_types/transform-occ/main.go
See [bug 1568471](https://bugzil.la/1568471) for context. Thanks!
=> Bug 1568471 - close HTTP response bodies when finished with them

runtime/runtime_darwin.go
See [bug 1567632](https://bugzil.la/1567632) for context. Thanks!
=> Bug 1567632 - internally cache interactive username (lazily) on macOS

aws_helper_test.go, gcp_helper_test.go, helper_test.go
See [bug 1553953](https://bugzil.la/1553953) for context. Thanks!
=> Bug 1553953 - place restrictions on test workerType naming

logging.go, main.go
See [bug 1565215](https://bugzil.la/1565215) for context. Thanks!
=> Bug 1565215 - include timezone in log timestamps and set to UTC

.taskcluster.yml, aws.go, aws_helper_test.go, aws_test.go, awsprovider.go, awsprovisioner.go, bootstrap.go, fileutil/file.go, gcp.go, gcp_helper_test.go, helper_test.go, main.go, worker_types/gwci-linux-beta/bootstrap.sh, workermanager.go
Let's see how the CI runs with this. It is mostly shuffling code around. If the CI passes, we should have reasonable coverage for AWS Provisioner and GCP. We can add tests for AWS Provider, but I haven't done that yet.
See [bug 1588834](https://bugzil.la/1588834) for context.
=> Bug 1588834 - add support for AWS provider

.taskcluster.yml, aws.go, docker_posix.yml, envvars_broken_on_docker_test.go, gcp.go, gcp_helper_test.go, gcp_test.go, generated_docker_darwin.go, generated_docker_linux.go, generated_multiuser_darwin.go, generated_multiuser_linux.go, generated_multiuser_windows.go, generated_simple_darwin.go, generated_simple_linux.go, gwconfig/config.go, helper_windows_test.go, main.go, multiuser_posix.go, multiuser_posix.yml, multiuser_windows.go, multiuser_windows.yml, simple_docker.go, simple_posix.yml, testdata/check-env.go, usage.go
See [bug 1590134](https://bugzil.la/1590134) for details.
=> Bug 1590134 - add support for RFC #0148

process/multiuser_posix.go
Curious if this simple change will fix the issue. Note, a more sophisticated code change is probably warranted, but this may be enough to get the test passing before the rewrite.
See [bug 1602512](https://bugzil.la/1602512) for context.
=> Bug 1602512 - also abort task commands that haven't started yet
