taskcluster/generic-worker

artifacts.go
artifacts_test.go
aws.go
main.go
model.go
show-workers/main.go
signedurlmanager.go
taskstatus.go
update-worker-type/update-worker-type.go

Upstream removed `CallSummary` and made some lint fixes.

Adapted to work with upstream changes in taskcluster-client-go

---

artifacts_test.go
livelog/livelog.go
livelog/livelog_test.go
main.go

Renamed all_commands.log to live_backing.log to fix links sent by mozilla-taskcluster to treeherder

---

artifacts_test.go
main.go

Hey Greg,
This should mirror docker worker behaviour, so that after a live log is no longer available, the livelog artifact is replaced by an alternative redirect artifact which points to the underlying log file.
The only difference is that we have one livelog per command in the Generic Worker, rather than just a single live log per task.

Bug 1277568: redirect livelog artifact to underlying log when task command completes

---

.travis.yml
README.md
artifacts_test.go
aws.go
config_test.go
main.go
mergeconfig.go
model.go
plat_all-unix-style.go
release.sh
test/config/worker-type-metadata.json
worker_types/ttaubert-win2012r2/userdata
worker_types/win2012r2/userdata

This is a place for storing information about how the worker type was set up. In the worker type definition, a json object can be set in `secrets.generic-worker.config.workerTypeMetadata` for adding extra data into `public/logs/worker_type_metadata.json`. Note, it comes with some default fields, which can be overridden or added to:
```json
{
"generic-worker-version": <generic-worker-version>,
"go-version":             runtime.Version(),
"go-arch":                runtime.GOARCH,
"go-os":                  runtime.GOOS
}
```
It is intended that this would be used for storing a link to the machine setup, _for example_, by adding something like this to the worker type definition:
```
{
"secrets": {
"generic-worker": {
"config": {
"workerTypeMetadata": {
"machine-setup": …
```

Bug 1279019: add artifact public/logs/worker_type_metadata.json to each task

---

plat_darwin.go
plat_windows.go

This is to help out with numerous firefox desktop build bugs. Theoretically we shouldn't need to change generic worker for this, but it is looking so tricky to fix on firefox side, that it just a pragmatic compromise.

Changed Task_<timestamp> dirs to task_<timestamp>

---

artifacts.go
artifacts_test.go
main.go
payloadmodel.go
plat_windows.go
show-workers/main.go
update-worker-type/update-worker-type.go

This depends on taskcluster/taskcluster-client-go#15 so I would expect travis to fail for this PR until that has landed. When the other PR lands, you should be able to rerun the travis jobs on this PR.

Bug 1285197 - fix go get warning for taskcluster-client-go

---

artifacts.go
artifacts_test.go
main.go
model.go
plat_all-unix-style.go
plat_windows.go

To be consistent with docker worker.

One livelog per task, instead of per command

---

artifacts.go
model.go
taskstatus.go

This should mean we no longer need to grant `queue:create-artifact:*` to all worker types that use generic worker.

Use credentials from queue.ClaimTask response for uploading artifacts

---

main.go

with more worker types taking jobs (win 7, 10 testers), it's handy to be able to see quickly which worker type is running the task

show worker type at start of task log

---

worker_types/win2012r2/userdata

I believe these commands should do it. I followed what is already done for BinScope.

Bug 1305048 - Add node 6.6.0 to win2012r2.

---

README.md
aws.go
clean-builds.sh
main.go
model.go
release.sh
worker_types/nss-win2012r2/userdata
worker_types/win2012r2/userdata

@grenade This is a first stab. Maybe we are lucky and it works first time, but it is complex enough that that might not be the case. It is kind of tricky to test in a unit test as it requires interaction with the provisioner, and I didn't really fancy creating fake worker types in integration tests. So I think the best is for me to make an alpha release, test it in `ami-test-win2012r2` worker type...

Bug 1298010 - shut down worker type if deploymentId has updated in worker type config

---

plat_windows.go

c4.4xlarge instances are being terminated by g-w before doing any work. papertrail [logs](https://papertrailapp.com/systems/532378943/events?focus=734832384771678217) contain only the shutdown command initiated by the g-w user and no reason for the halt (eg: "Nov 14 07:02:18 i-06272f1dc5bf6e4e9.gecko-1-b-win2012-beta.euc1.mozilla.com User32:  The process C:\Windows\System32\shutdown.exe (I-06272F1DC5BF6) has initiated the shutdown of computer I-06272F1DC5BF6 on behalf of user I-06272F1DC5BF6\GenericWorker for the following reason: No title for this reason could be found   Reason Code: 0x800000ff   Shutdown Type: shutdown   Comment:  "). by delaying the shutdown, i am hoping to capture the g-w logs before the instance is terminated.

bug 1307204 - give system time to log exceptions

---

all-unix-style.yml
artifacts.go
artifacts_test.go
chain_of_trust.go
generated_all-unix-style.go
generated_windows.go
livelog.go
taskstatus_test.go
windows.yml

@grenade Feel free to take a look at this too and give feedback! I can't assign you as a reviewer as it looks like you're not a member of the repo - I can look at fixing that too.
Note this fix allows you to specify an optional artifact name, which if not specified, defaults to the artifact path, in order to maintain backwards compatibility.
This is needed for the OS X rollout, since the symlink trick doesn't work on OS X as it does on Windows.

Bug 1352457 - support optional artifact name

---

.gitignore

The first time running `generic-worker run` a configuration file is created which should not be checked in.

Ignore configuration file created by generic-worker

---

.taskcluster.yml
artifacts.go

This was causing some crashes, such as [this log extract](https://papertrailapp.com/systems/812287681/events):
```
Apr 15 16:09:29 i-04638966ed4f61a5f.gecko-t-win7-32.use1.mozilla.com generic-worker: 2017/04/15 14:09:27 Resolving task... 
Apr 15 16:09:30 i-04638966ed4f61a5f.gecko-t-win7-32.use1.mozilla.com generic-worker: 2017/04/15 14:09:28 goroutine 1 [running]: 
Apr 15 16:09:30 i-04638966ed4f61a5f.gecko-t-win7-32.use1.mozilla.com generic-worker: runtime/debug.Stack(0x0, 0x0, 0x0) 
Apr 15 16:09:30 i-04638966ed4f61a5f.gecko-t-win7-32.use1.mozilla.com generic-worker: 	/home/travis/go/src/runtime/debug/stack.go:24 +0x80 
Apr 15 16:09:30 i-04638966ed4f61a5f.gecko-t-win7-32.use1.mozilla.com generic-worker: main.RunWorker.func1() 
Apr 15 16:09:30 …
```

Bug 1356800 - avoid nil pointer exception when uploading artifacts

---

.taskcluster.yml
README.md
artifacts.go
artifacts_test.go
chain_of_trust.go
livelog.go
main.go

This now uses a blacklist of file extensions to _not_ gzip compress, everything else gets gzip content-encoding. Based on this [blacklist](https://github.com/evansd/whitenoise/blob/03f6ea846394e01cbfe0c730141b81eb8dd6e88a/whitenoise/compress.py#L21-L29).
CC @edmorley @gregarndt @jonasfj

Bug 1347956 - gzip more artifacts

---

README.md

Simply running `generic-worker --config CONFIG-FILE` displays usage, presumably because it's required to include the *run* target in the invocation.

include name of generic-worker target

---

mounts_windows_test.go
plat_windows.go

Added support for moving folders across Windows volumes. This is useful so that writable caches can be stored on a _different_ volume to task folders, so e.g. we can format the drive with task folders between tasks (typically `Z:\`) without losing caches and downloads which can now be placed on e.g. `Y:\` or `C:\`.
Previously, caches had to be on the same drive (volume) as the task folders.

Rename folder cross device windows

---

all-unix-style.yml
artifacts_test.go
chain_of_trust.go
docs/features.md
generated_all-unix-style.go
generated_windows.go
windows.yml

@Callek @escapewindow This should correct the chain of trust artifact name.

public/logs/chainOfTrust.json.asc => public/chainOfTrust.json.asc

---

README.md
artifacts.go
main.go
model.go
monitor.go
monitor_test.go
testdata/config/bool-as-string.json
testdata/config/valid.json
testdata/config/worker-type-metadata.json

Based on taskcluster-worker monitor package, we implement monitoring
support on generic-worker.

Port t-w monitor package to g-w.

---

.taskcluster.yml
.travis.yml
all-unix-style.yml
fileutil/fileutil.go
generated_all-unix-style.go
generated_windows.go
gwconfig/config.go
main.go
mounts.go
supersede.go
supersede_test.go
windows.yml

This initial implementation is simpler than the docker-worker implementation.  I have chosen an initial simpler implementation for the following reasons:
1. it is simpler, and therefore less likely to break or contain bugs, which is important as I will be on PTO for two weeks
2. I also believe it is a better implementation
Differences to docker-worker implementation
Docker worker claims all tasks it finds listed in the superseded service response body. It keeps claims on those tasks while the primary task (the task it has claimed which is not superseded by any other tasks it has claimed) is running. It then resolves all tasks upon completion of the primary task, attaching artifacts to identify which task run superseded a given task run, and which tasks were superseded by a given task run. …

Bug 1383024 - Superseding

---

artifacts.go

I decided to retry _all_ HTTP 400 errors, rather than just trying to catch connection inactivity ones, since a production 400 error should be a relatively rare event (generally implying a bug in the code).

Bug 1394557 - retry artifact uploads with HTTP 400 status code response

---

supersede.go
supersede_test.go

Previously, [generic-worker would crash](https://public-artifacts.taskcluster.net/Ya39sUGTSgmR9BOa65ogcA/4/public/logs/live_backing.log) if the supersedes list was empty.
Fixed, and added a test to check for it.

Bug 1382204 - handle empty supersedes list

---

taskstatus.go

Locking shouldn't be required in this case, as generic-worker creates task.Queue on task initialisation in the main go routine, before other go routines are spawned that access it. Therefore there should be no races.
Thanks Jonas!

Bug 1402152 - use creds returned from claimWork to reclaim and resolve tasks

---

sentry.go

This should make troubleshooting a bit easier.

Bug 1415088 - include generic-worker version, GOOS and GOARCH in sentry reports

---

all-unix-style.yml
artifacts.go
artifacts_test.go
generated_all-unix-style.go
generated_windows.go
helper_test.go
livelog.go
main_test.go
supersede.go
taskstatus_test.go
windows.yml

This should allow people to explicitly set `Content-Type` of artifact resources if they are not happy with the default choice of the system.

Bug 1423215 - Make contentType an optional property of file artifact in task payload

---

artifacts.go
main.go
main_test.go
mounts.go
os_groups.go
plat_windows.go
process/process_windows.go
supersede.go
taskstatus.go

I've split up each of the two task logging methods into a pair of Info / Error methods, to distinguish if they are error lines or info lines:
```
task.Log(...)
-> task.Info(...)
-> task.Error(...)
task.Logf(...)
-> task.Infof(...)
-> task.Errorf(...)
```
Then in each logging call, I've made an executive decision about if it is an info or an error log message.
In line with [this comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1333957#c12) error logs are now written like:
```
[taskcluster:error] <message>
```
Info log messages are written like:
```
[taskcluster <timestamp>] <message>
```
This is likely to be updated later to provide a timestamp in the error message too, but for now this would break treeherder log parsing, so will only be done once treeherder can accept the input.
I've …

Bug 1333957 - differentiate error and info log lines

---

artifacts_test.go
chain_of_trust.go
chain_of_trust_all-unix-style.go
chain_of_trust_windows.go
helper_test.go
main.go
plat_windows.go
plat_windows_test.go
process/process_windows.go

1) Don't start worker if the chain of trust key cannot be read or has invalid content.
2) Don't start the worker if the chain of trust key can be read by a task user.

Bug 1358545 - check file permissions of chain of trust key and validity of content on startup

---

main.go
mounts.go

Currently the purging of caches is the responsibility of the `MountsFeature`. Unfortunately, features operate on claimed tasks, so in the current implementation, a task is claimed before the feature has had a chance to see if it can free up enough disk space for the task. When it becomes unable to execute the task, because it lacks disk space, it has no choice but to resolve the task with the exception state.
This PR moves the purging of caches outside of the feature, into the generic worker task claim loop, immediately before a task is claimed. This way, the worker knows ahead of time that it won't be able to claim a task, and is able to exit gracefully, without sacrificing any task runs on the way.
The reason it was originally implented like this, was to localise the management of …

Bug 1441482 - free up disk space between tasks, not after task claim

---

build.sh
chain_of_trust_windows.go
plat_windows.go
process/process_windows.go

Now go 1.10 supports running processes using `CreateProcessAsUser` on Windows in the standard library, so this PR uses it.

Bug 1447265 - use os/exec package on Windows too

---

process/process_windows.go

We weren't setting an appropriate environment for processes running as a different user.

Environment fix

---

livelog.go
main.go
model.go
process/process_windows.go
taskcluster_proxy.go
taskstatus.go

This is a cleanup of the reclaim logic, to put it all in the `TaskStatusManager`. Callers don't need to concern themselves with reclaims, when you create the `TaskStatusManager`, it now starts the reclaims in a private (non-exported) background go routine. When a task is aborted or completes naturally, the reclaiming automatically stops.

Move task reclaims into TaskStatusManager

---

main.go

In the early days, we used to search for and delete task directories under `config.TasksDir` directory, which would e.g. scan `Z:\` and delete directories like:
```
Z:\task_1527860330
```
Since the system user profiles directory is typically elsewhere (e.g. `C:\Users`), sometimes tasks ended up writing to both the task directory (e.g. `Z:\task_1527860330`) and the user profile directory (e.g. `C:\Users\task_1527860330`).
To reduce the occurrences of this, we made sure that `APPDATA` and `LOCALAPPDATA` point inside the task directory, but e.g. `TMP` and `TEMP` are defined in the Default User Profile, may still point inside the system user profiles directory. Note, Microsoft do not support changing the location of the system user profiles directory after Windows has been installed - it …

Bug 1433854 - delete old task user profile directories

---

.taskcluster.yml
artifacts.go
artifacts_test.go
chain_of_trust.go
feature.go
garbagecollector.go
helper_all-unix-style_test.go
helper_windows_test.go
livelog.go
main.go
main_test.go
mounts.go
mounts_test.go
os_groups.go
plat_all-unix-style.go
process/process_windows.go
rdp_windows.go
supersede.go
taskcluster_proxy.go
taskstatus.go
testdata/move-file.go
testdata/spawn-orphan-process.go
update-ssl-creds/main.go

See [bug 1465479](https://bugzilla.mozilla.org/show_bug.cgi?id=1465479) for context.
This was originally a TODO from [#92](https://github.com/taskcluster/generic-worker/pull/92#issuecomment-390289022).
Let's wait for CI to run before reviewing it.
Note I don't currently have a test that reproduces [the regression we saw in production](https://bugzilla.mozilla.org/show_bug.cgi?id=1465112#c3) - I'm not sure what circumstances are required for `taskkill.exe /t` to complete successfully, but `cmd.Wait()` not to immediately return. Presumably it requires creating a subprocess that inherits stdin/stout/stderr handles but starts its own process tree, if such a thing is allowed.
Let me know if you think writing such a test is worthwhile.

Bug 1465479 - Don't block task abortion waiting for cmd.Wait() to complete

---

livelog.go
livelog/livelog.go
livelog/livelog_test.go

Previously, we started the livelog process, and then polled the PUT port for up to one minute to wait for it to be active.
If the livelog process returns while we are waiting for the port to be active, we know something has gone wrong, and can immediately return an error, rather than waiting the full minute to return an error.
This change also tracks the command output from the livelog command, so that if the process does fail, we have the output from the command logged in the task's backing log which gets uploaded when the task is resolved.

Bug 1466803 - detect if livelog process terminates before PUT port is active

---

.taskcluster.yml

We do this since `taskId`s may start with `-`, for example, if retriggered using a tool that doesn't use _nice_ slugs.

Prefix generated git branch names with X 

---

all-unix-style.yml
generated_all-unix-style.go
generated_windows.go
helper_all-unix-style_test.go
helper_windows_test.go
main.go
main_test.go
windows.yml

This is an attempt at adding `onExitStatus` like we have in docker-worker. If what I've done here mostly makes sense maybe you can give some pointers on testing that I should do and I'll try to do that tomorrow!
Note 1: This appears to work from running the worker locally and submitting test jobs.
Note 2: I'm not sure why the tests are failing? Something to do with `git status` on the mac builder at least.

Bug 1469402 - Add a onExitStatus section to the payload

---

mozilla-try-scripts/gecko-try.sh
mozilla-try-scripts/gecko.patch
mozilla-try-scripts/lib/tooltool.py
mozilla-try-scripts/nss-try.sh
mozilla-try-scripts/nss.patch
mozilla-try-scripts/waitforOCC.go

Hey Brian,
I took a first pass at moving these scripts into the repository. It isn't beautiful and the end state I'd like it to be in, but it unblocks other people from trying these things out.
I haven't gone heavy on docs, because I really want to rewrite the whole thing, probably in go, and ideally have it triggered via a git interaction of some kind. I haven't worked out the place for this yet, but my feeling is we should be using some kind of existing access controls (whether those are github access controls or taskcluster or some other system access controls I'm not sure) but some simple interaction should be able to select a generic-worker release (default being latest) and then choose to make a test gecko push with it, or nss, or both. On the way, sensible defaults, but having the …

Added utility scripts for testing new generic-worker releases on try

---

main.go

This should fix #109. Note, in our current configuration, we were running generic-worker on windows with `C:\generic-worker` as the working directory, so using a relative path for the caches and downloads directories won't change anything on our windows workers, but having a relative path will mean sensible defaults for other platforms. Note these are only defaults, so workers can use different directories if they prefer.

Make defaults for CachesDir and DownloadsDir a relative path

---

process/process_all-unix-style.go

See [bug 1475689](https://bugzil.la/1475689) for context.
Calling https://golang.org/pkg/os/exec/#Cmd.Wait can mean that you wait forever if a process gets stuck and can't be killed when a task is aborted.
Instead, signal task abortion via the closing of a go channel so that task abortion can be handled in parallel to process termination. This was already implemented on Windows, this applies a similar fix for all other platforms.

Bug 1475689 - don't wait for commands to complete with (*os/exec.Cmd).Wait()

---

all-unix-style.yml
generated_all-unix-style.go
main.go
os_groups.go
os_groups_all-unix-style.go
os_groups_all-unix-style_test.go
os_groups_windows.go
os_groups_windows_test.go
plat_windows.go

See [bug 1480412](https://bugzil.la/1480412) for more details.
Since `osGroups` feature isn't supported on non-Windows platforms currently, in the most recent release (10.11.2) I had moved the `osGroups` code into the Windows codebase (`*_windows.go` files) from the cross platform go files. I hadn't realised that the gecko task generation code was creating non-Windows tasks specifying an empty `osGroups` list (`[]`). Rather than fix the task generation in all gecko trees/branches (and any other projects that might be doing the same) not to allow `osGroups` for platforms where this feature is not implemented, this PR ensures that the only acceptable value for `osGroups` on a non-Windows platform is the empty list (i.e. "no groups").
The reason it isn't implemented on those other platforms …

Bug 1480412 - allow empty osGroups list on non-Windows platforms

---

build.sh

This PR addresses the following fixes:
* `gw-codegen` not in PATH
* `golint` not installed
* `taskcluster-proxy` not installed

added missing dev-env setup steps to build.sh

---

worker_types/nss-win2012r2/userdata

We need to run 3.2 if we're going to use the vswhere tool to find VS.  That won't change the calculus for these builds, but it's a big usability improvement for contributors.

Bug 1434943 - Update MozillaBuild version to 3.2 for NSS

---

main.go
plat_windows.go
worker_types/ami-test-win2012r2/userdata
worker_types/ami-test-win7sp1/userdata
worker_types/nss-win2012r2-new/userdata
worker_types/nss-win2012r2/userdata
worker_types/win2012r2-cu/userdata
worker_types/win2012r2/userdata
worker_types/win2016/userdata

See [bug 1495435](https://bugzilla.mozilla.org/show_bug.cgi?id=1495435).
Previously, the generic-worker `install` target on Windows created a `run-generic-worker.bat` script that called `generic-worker run --configure-for-aws`, i.e. it made the assumption that the worker ran in AWS.
This PR adds the existing `--configure-for-aws` option of `generic-worker run` to `generic-worker install`. If (and only if) `--configure-for-aws` is specified when calling `generic-worker install`, the generated `run-generic-worker.bat` script will include `--configure-for-aws` in the `generic-worker run` command.
In other words, you now choose at _install_ time if this installation is for AWS workers, and the correct option is passed down to the `generic-worker run` command.

Bug 1495435 - Make --configure-for-aws a configurable option at install time

---

livelog.go
main.go
model.go

See [bug 1486800](https://bugzil.la/1486800) for details.

Bug 1486800 - don't start max run timer before task initialisation has completed.

---

helper_all-unix-style_test.go
helper_windows_test.go
main_test.go
process/process_all-unix-style.go

See [bug 1479415](https://bugzil.la/1479415) for context.

Bug 1479415 - tasks executing a non-executable file should resolve as failed, not exception

---

all-unix-style.yml
generated_all-unix-style.go
generated_windows.go
mounts.go
mounts_test.go
windows.yml

Adding support for **RawContent**(text) and **Base64Content** as mount options as requested in [Bug 1495732](https://bugzilla.mozilla.org/show_bug.cgi?id=1495732).

Bug 1495732 - support inline content when mounting files/directories

---

build.sh

We are not sure why this was here - perhaps a copy-paste error?  But it
deletes local files that I would like it not to delete!

remove 'git clean' command from build process

---

aws.go
aws_helper_test.go
gwconfig/config.go
helper_test.go
main.go
main_test.go
mounts.go
sentry.go
taskstatus.go
testdata/resolvetask.go

Hey @jhford,
See [bug 1469614](https://bugzil.la/1469614). This updates generic-worker to use the new taskcluster-client-go that appeared in [bug 1428422](https://bugzil.la/1428422). I may have missed something on this first commit, so let's wait for the CI to complete, and also then I'll check the CI logs to make sure no tests were skipped for any reason. I'll put you up for review as soon as I'm confident it is ready.
Thanks!

Bug 1469614 - use updated taskcluster-client-go in generic-worker

---

worker_types/nss-win2012r2-new/userdata
worker_types/nss-win2012r2/userdata
worker_types/win2012r2/userdata

Sorry John, I needed to make a new release. This patch is like the last one, just a different version number! :-)
See [bug 1523911](https://bugzil.la/1523911) for details.

Bug 1523911 - Upgrade to taskcluster-proxy 5.1.0 on all worker types

---

aws_helper_test.go
config_test.go
gcp.go
gcp_helper_test.go
gcp_test.go
main.go
plat_windows.go

This _works_ but might not be the way we want to do it in the future. Please feel free to have me change how anything works.
This works in concert with https://github.com/imbstack/taskcluster-gce-provider-concept.
Specifically the tc creds comes from [here](https://github.com/imbstack/taskcluster-gce-provider-concept/blob/master/src/api.js)
We can wait on merging this until rootUrl support exists.

Support GCE as an environment

---

README.md
main.go

`generic-worker --help` should state that `*BaseURL` settings are optional overrides for the global `rootURL` setting.
See [bug 1524630](https://bugzil.la/1524630) for context.
Note, the `README.md` update is just a consequence of running the `refresh_readme.sh` script in the root directory, which regenerates `README.md` based on the output of `generic-worker --help`.

Bug 1524630 - `generic-worker --help` improvements

---

aws.go
config_test.go
main.go

In other words, we should only inspect aws/gcp metadata if generic-worker config file is missing, which happens on first run of the worker. On subsequent runs (e.g. after a reboot) the config file is present and written to disk, so no metadata queries or calls to the AWS Provisioner are made.
This means you now can't have a subset of generic-worker config on the filesystem, and merge it with what you get from the metadata service / secrets service - but that is probably a good thing. Previously you could do this, but then it would have been misleading for people looking at the worker type definition, since there would be potentially incorrect config settings there that were getting overridden with what was stored e.g. in the AMI.
Now if you get credentials from the provisioner, you also …

Bug 1375200 - only update config from aws/gcp if generic worker config not present

---

main.go

I was debugging why generic-worker wouldn't start and found that the same error code was returned for two states. This PR attempts to make debugging easier.

add additional exit code

---

artifacts.go
artifacts_test.go

See [bug 1532588](https://bugzil.la/1532588) for details.

Bug 1532588 - use reflect.DeepEqual rather than fmt.Sprintf("%q") for testing equality

---

artifacts.go
fileutil/fileutil_all-unix-style.go
gwconfig/config.go
main.go
mounts.go
process/process_all-unix-style.go
process/process_windows.go
win32/win32acl_windows.go
yamltojson/main.go

Hi, we updated some exported function comments based on best practices from [Effective Go](https://golang.org/doc/effective_go.html). It’s admittedly a relatively minor fix up. Does this help you?

Fix function comments based on best practices from Effective Go

---

mounts.go

See [bug 1543082](https://bugzil.la/1543082) for more context.
See [sentry issue GENERIC-WORKER-1J](https://sentry.prod.mozaws.net/operations/generic-worker/issues/5508600/).

Bug 1543082 - only log to task logs if task is running

---

main.go
main_test.go
plat_all-unix-style.go
plat_windows.go

See [bug 1533694 comment 4](https://bugzilla.mozilla.org/show_bug.cgi?id=1533694#c4) for context.
In `generic-worker 14.0.1` the code executed from the `runAfterUserCreation` config setting was run not in the task directory of the current task user, but in the task directory that has been prepared for the subsequent task user. This fixes this bug and simplifies the code paths a little.

Bug 1533694 - fix to run runAfterUserCreation code in current task directory

---

expose/statelessdns.go
expose/statelessdns_test.go
livelog.go
main.go

The first fixes a silly bug: I was passing filenames where PEM data was expected.
The second is a little more significant: without this change, exposer serves exposed things on an arbitrary port, but of course we don't have arbitrary ports open.  We have a single port open, which is labeled "livelogGETPort" in the configuration.  So, we configure the stateless DNS exposer to always expose on that port.  The similarly-named "livelogPUTPort" is not really similar -- it's used for communication between the task execution and the livelog process.  That's really an implementation detail and should probably be moved out of the config eventually.  And, once stateless DNS is turned off, we can get rid of `livelogCertificate`, `livelogGETPort`, `livelogKey`, and `livelogSecret`.
This ran a task …

Bug 1436195 - fix livelog certs, port

---

worker_types/ami-test-win2012r2/userdata
worker_types/ami-test-win7sp1/userdata
worker_types/deepspeech-win-gpu-b/userdata
worker_types/gecko-1-b-win2012-beta/userdata
worker_types/gecko-1-b-win2012/userdata
worker_types/gecko-2-b-win2012/userdata
worker_types/gecko-3-b-win2012/userdata
worker_types/gecko-t-win10-64-beta/userdata
worker_types/gecko-t-win10-64-cu/userdata
worker_types/gecko-t-win10-64-gpu-b/userdata
worker_types/gecko-t-win10-64-gpu/userdata
worker_types/gecko-t-win10-64/userdata
worker_types/gecko-t-win7-32-beta/userdata
worker_types/gecko-t-win7-32-cu/userdata
worker_types/gecko-t-win7-32-gpu-b/userdata
worker_types/gecko-t-win7-32-gpu/userdata
worker_types/gecko-t-win7-32/userdata
worker_types/nss-win2012r2-new/userdata
worker_types/nss-win2012r2/userdata
worker_types/win2012r2-cu/userdata
worker_types/win2012r2/userdata
worker_types/win2016/userdata

This recently moved -- https://github.com/mozilla/build-tooltool/

look for tooltool in the new location

---

README.md

it wasn't immediately clear to me why `go get github.com/taskcluster/generic-worker` resulted in errors, this should clear some of that up

README.md: mention build.sh in building from source instructions

---

.taskcluster.yml
main.go
mounts_broken_on_docker_test.go
plat_all-unix-style_test.go
plat_windows_test.go

For workers that run more than one task per generic-worker invocation, the task directory creation and purging logic was broken with the code changes from [bug 1533694](https://bugzil.la/1533694), meaning that only a single task directory was created per generic-worker invocation, rather than between every task.
This impacted macOS and linux workers. The fix is to move the task directory creation and task directory purging into the main loop that claims and executes tasks.

Bug 1551164 - move create/purge task directory steps into task-claim-and-execute loop

---

.taskcluster.yml
README.md
fileutil/fileutil.go
kc/kc.go
kc/kc_test.go
multiuser.go
multiuser_posix.go
multiuser_windows.go
process/multiuser_posix.go
runtime/runtime_darwin.go
runtime/runtime_posix.go
runtime/runtime_windows.go

See [bug 1560388](https://bugzilla.mozilla.org/show_bug.cgi?id=1560388) for context.

Bug 1560388 - don't update macOS autologin settings within 10 seconds of user login

---

docker_posix.yml
generated_docker_darwin.go
generated_docker_linux.go
generated_multiuser_darwin.go
generated_multiuser_windows.go
generated_simple_darwin.go
generated_simple_linux.go
multiuser_posix.yml
multiuser_windows.yml
simple_posix.yml

This updates the task payload schemas to explicitly mention which environment variables are automatically set in task commands.
See [bug 1382668](https://bugzil.la/1382668) for context.

Bug 1382668 - Add information to docs about automatically set environment variables

---

build.sh
fileutil/fileutil_posix.go
host/host.go
host/host_posix.go
host/host_windows.go
kc/kc.go
main.go
mounts_multiuser.go
multiuser.go
multiuser_posix.go
multiuser_windows.go
process/docker.go
process/multiuser_posix.go
process/multiuser_windows.go
process/simple.go
runtime/runtime.go
runtime/runtime_darwin.go
runtime/runtime_windows.go
simple_docker.go
usage_posix.go

See [bug 1567073](https://bugzil.la/1567073) for context.
I created a separate package (`host`) to avoid some cyclic dependencies we would have otherwise had. The idea is, this should be anything you want to do to interact with the host operating system, rather than interacting with e.g. a container/sandbox. At the moment it just contains an existing `RunCommands` function that I moved straight over from `runtime` package, and a new `RunCommand` utility method to log the command about to be run, run it, check if it fails, and if so log the combined stderr/stdout, and returns the command output and error. For convenience, it converts the output from `[]byte` to `string` since in 99% of cases that is what we want.
The other changes are just to use it, so we have a single function where we …

Bug 1567073 - log all commands that are executed on the host

---

.taskcluster.yml

For generic-worker CI tests, we need a taskcluster client with a limited set of scopes. On some worker types, we previously burned in a client on the workers, but this has some disadvantages:
1) It means rotating the client requires updating all workers that use it, which can be some work
2) It is less clear / discoverable where the client comes from, from the task definition
3) It makes it harder for users that should be able to see the secret, to see it
By updating the CI tasks to consistently fetch the secret from taskcluster-secrets, it removes the need to burn it into workers, which can then also be used for other tasks too that shouldn't have access to this secret, if needed.

Fetch taskcluster test credentials from taskcluster-secrets

---

.taskcluster.yml

Hey @djmitche,
As far as I understand, this CI task is no longer needed, since we no longer publish worker docs to taskcluster-docs. Do you agree?
If we do still need the docs to be published from the CI, feel free to close this PR.
Thanks.

No longer publish worker docs in CI using taskcluster-lib-docs

---

runtime/runtime_darwin.go

Whoops!
See [bug 1592233](https://bugzil.la/1592233) for context. These two lines [used to exist](https://github.com/taskcluster/generic-worker/commit/814aa9e8afee3e925b1295eeda12841da8754404#diff-db028d655af10079249eb4d4a2b5120cL29-L30) but got deleted because I thought they were no longer needed, but it seems they were.
Since I hadn't upgraded any mac workers, I hadn't spotted that this was broken, and unfortunately the unit and integration tests didn't catch it.

Bug 1592233 - calculate UID for new user under macOS multiuser

---

aws.go
aws_broken_on_docker_test.go
aws_helper_test.go
aws_test.go
awsprovider.go
awsprovisioner.go
config_test.go
gcp.go
gcp_helper_test.go
gwconfig/config.go
gwconfig/provider.go
helper_test.go
main.go
worker_types/gwci-linux-beta/bootstrap.sh
workermanager.go

See [bug 1593483](https://bugzil.la/1593483) for additional context.
I think this should do it. It is pretty tricky to test.
The problem we had before was that if config file was found on the file system, we avoided the config negotiation with AWSProvisioner/WorkerManager and used the config file we had persisted. However, the function to check for a new `deploymentId` was therefore not updated, so the check for a new `deploymentId` was using the default function which just checked the local generic-worker config file, rather than talking to AWSProvisioner/WorkerManager.
The way I've solved this turned out to be a bit of a rewriting, so that we have a `gwconfig.Provider` interface that has a method for updating generic-worker config, and for fetching the latest deployment ID.

Bug 1593483 part 2

---

runtime/runtime_windows.go

This worked in my local testing, but I'm not sure if this will upset generic-worker running on Windows 7 32 bit (386) edition.

Bug 1595279 - explicitly write to _64 bit_ winlogon registry keys

---

README.md
aws_helper_test.go
azure.go
config_test.go
gcp_helper_test.go
main.go
multiuser_windows.go
usage.go
workermanager.go

This PR adds `--configure-for-azure` option to generic-worker to unblock Azure work.

Added --configure-for-azure option for running in Azure cloud

---

main.go

(This means that 16.6.0 is nonfunctional)

Fix panic when --worker-runner-protocol-pipe is not supplied
